server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: jspnate2919!

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 318911870323-45qo9rkq0asrfbo2jba6mauuh966h51v.apps.googleusercontent.com
            client-secret: ULTCiBo1u1dvTmehBj1ywr0_
            scope:
              - email
              - profile

          facebook:
            client-id: 1025971171545704
            client-secret: f8b998411685a181b0f67fc72054ed21
            scope:
              - email
              - public_profile

          naver:
            client-id: EoQSd796FEMLdqpCDjjh
            client-secret: QXymThd__Y
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키 값으로 리턴해줌.



# 로그로 출력
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace