spring:
  application:
    name: naver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hiberante.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=Asia/Seoul
    username: sa
    password: jspnate2919!